/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.huellitas.view;

/**
 *
 * @author yisha
 */
public class FormProductos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormProductos.class.getName());

    /**
     * Creates new form FormProductos
     */
    public FormProductos() {
        initComponents();
        this.setLocationRelativeTo(null); // Centra la ventana en la pantalla
    listarProductos(); // Carga la lista de productos al abrir
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreLb = new javax.swing.JLabel();
        codigoLb = new javax.swing.JLabel();
        stockLb = new javax.swing.JLabel();
        stockMinimoLb = new javax.swing.JLabel();
        precioLb = new javax.swing.JLabel();
        nombreTF = new javax.swing.JTextField();
        codigoTF = new javax.swing.JTextField();
        stockTF = new javax.swing.JTextField();
        stockMinimoTF = new javax.swing.JTextField();
        precioTF = new javax.swing.JTextField();
        guardarBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        productosTbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nombreLb.setText("Nombre:");

        codigoLb.setText("Código:");

        stockLb.setText("Stock:");

        stockMinimoLb.setText("Stock Mínimo:");

        precioLb.setText("Precio:");

        nombreTF.addActionListener(this::nombreTFActionPerformed);

        codigoTF.addActionListener(this::codigoTFActionPerformed);

        guardarBtn.setText("Guardar");
        guardarBtn.addActionListener(this::guardarBtnActionPerformed);

        productosTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Código", "Nombre", "Stock", "Stock Mínimo", "Precio"
            }
        ));
        jScrollPane1.setViewportView(productosTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigoLb, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stockLb, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stockMinimoLb)
                            .addComponent(precioLb, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreLb, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(precioTF, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                    .addComponent(stockMinimoTF)
                                    .addComponent(stockTF))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(guardarBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(codigoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoLb)
                    .addComponent(codigoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nombreLb)
                    .addComponent(nombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stockLb)
                    .addComponent(stockTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stockMinimoLb)
                    .addComponent(stockMinimoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioLb)
                    .addComponent(precioTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guardarBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTFActionPerformed

    private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed
        // TODO add your handling code here:                                           
    try {
        // Leemos lo que el usuario escribió en las cajas de texto
        String codigo = codigoTF.getText().trim();
        String nombre = nombreTF.getText().trim();
        
        if (codigo.isEmpty() || nombre.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor completa el código y el nombre.");
            return;
        }

        int stock = Integer.parseInt(stockTF.getText().trim());
        int stockMinimo = Integer.parseInt(stockMinimoTF.getText().trim());
        double precio = Double.parseDouble(precioTF.getText().trim());

        // Creamos el objeto Producto y llamamos al DAO
        com.huellitas.model.Producto p = new com.huellitas.model.Producto(codigo, nombre, stock, stockMinimo, precio);
        com.huellitas.dao.ProductoDAO dao = new com.huellitas.dao.ProductoDAO();

        if (dao.registrar(p)) {
            javax.swing.JOptionPane.showMessageDialog(this, "¡Producto guardado exitosamente!");
            limpiarCampos();
            listarProductos(); // Refresca la tabla automáticamente
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar el producto en la base de datos.");
        }
        
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Asegúrate de ingresar números válidos en Stock, Stock Mínimo y Precio.");
    }
    }//GEN-LAST:event_guardarBtnActionPerformed

    private void codigoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormProductos().setVisible(true));
    }
    // 1. Método para cargar los datos en la JTable
private void listarProductos() {
    com.huellitas.dao.ProductoDAO dao = new com.huellitas.dao.ProductoDAO();
    java.util.List<com.huellitas.model.Producto> lista = dao.listar();
    
    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) productosTbl.getModel();
    
    // Limpiamos las filas anteriores
    modelo.setRowCount(0);
    
    // Si la tabla no tiene las columnas configuradas aún, se las ponemos
    if (modelo.getColumnCount() == 0) {
        modelo.addColumn("ID");
        modelo.addColumn("Código");
        modelo.addColumn("Nombre");
        modelo.addColumn("Stock");
        modelo.addColumn("Stock Mín.");
        modelo.addColumn("Precio");
    }
    
    // Llenamos la tabla fila por fila
    for (com.huellitas.model.Producto p : lista) {
        Object[] fila = new Object[6];
        fila[0] = p.getIdProducto();
        fila[1] = p.getCodigo();
        fila[2] = p.getNombre();
        fila[3] = p.getStock();
        fila[4] = p.getStockMinimo();
        fila[5] = p.getPrecio();
        modelo.addRow(fila);
    }
}

// 2. Método para limpiar las cajas de texto tras guardar
private void limpiarCampos() {
    codigoTF.setText("");
    nombreTF.setText("");
    stockTF.setText("");
    stockMinimoTF.setText("");
    precioTF.setText("");
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel codigoLb;
    private javax.swing.JTextField codigoTF;
    private javax.swing.JButton guardarBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombreLb;
    private javax.swing.JTextField nombreTF;
    private javax.swing.JLabel precioLb;
    private javax.swing.JTextField precioTF;
    private javax.swing.JTable productosTbl;
    private javax.swing.JLabel stockLb;
    private javax.swing.JLabel stockMinimoLb;
    private javax.swing.JTextField stockMinimoTF;
    private javax.swing.JTextField stockTF;
    // End of variables declaration//GEN-END:variables
}
