/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.huellitas.view;

/**
 *
 * @author yisha
 */
import com.huellitas.dao.MascotaDAO;
import com.huellitas.model.Mascota;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormMascota extends javax.swing.JFrame {

    MascotaDAO mascotaDAO = new MascotaDAO();
    DefaultTableModel modeloTabla = new DefaultTableModel();
    int idMascotaSeleccionada = -1;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormMascota.class.getName());

    /**
     * Creates new form FormMascota
     */
  
public FormMascota() {
        initComponents();
        this.setLocationRelativeTo(null); // Centra la ventana
        listarMascotas();
    }
private void listarMascotas() {
    List<Mascota> lista = mascotaDAO.listar();
    modeloTabla = (DefaultTableModel) jTable1.getModel();
    modeloTabla.setRowCount(0); // Limpia la tabla
    
    for (Mascota m : lista) {
        Object[] fila = new Object[6];
        fila[0] = m.getIdMascota();
        fila[1] = m.getNombre();
        fila[2] = m.getEspecie();
        fila[3] = m.getRaza();
        fila[4] = m.getEdad();
        fila[5] = m.getIdCliente();
        modeloTabla.addRow(fila);
    }
}

private void limpiarCampos() {
    NombreTF.setText("");
    EspecieTF.setText("");
    RazaTF.setText("");
    EdadTF.setText("");
    IdClienteTF.setText(""); // Nombre de la casilla de ID Cliente
    idMascotaSeleccionada = -1;
    jTable1.clearSelection();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NombreLb = new javax.swing.JLabel();
        EspecieLb = new javax.swing.JLabel();
        RazaLb = new javax.swing.JLabel();
        EdadLb = new javax.swing.JLabel();
        NombreTF = new javax.swing.JTextField();
        EspecieTF = new javax.swing.JTextField();
        RazaTF = new javax.swing.JTextField();
        EdadTF = new javax.swing.JTextField();
        GuardarBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ModificarBtn = new javax.swing.JButton();
        EliminarBtn = new javax.swing.JButton();
        IdClienteLb = new javax.swing.JLabel();
        IdClienteTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NombreLb.setText("Nombre:");

        EspecieLb.setText("Especie:");

        RazaLb.setText("Raza:");

        EdadLb.setText("Edad/años:");

        GuardarBtn.setText("Guardar");
        GuardarBtn.addActionListener(this::GuardarBtnActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Especie", "Raza", "Edad", "ID Cliente"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        ModificarBtn.setText("Modificar");
        ModificarBtn.addActionListener(this::ModificarBtnActionPerformed);

        EliminarBtn.setText("Eliminar");
        EliminarBtn.addActionListener(this::EliminarBtnActionPerformed);

        IdClienteLb.setText("ID Cliente:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EliminarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ModificarBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(IdClienteLb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NombreLb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EspecieLb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RazaLb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EdadLb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NombreTF)
                            .addComponent(EspecieTF)
                            .addComponent(RazaTF)
                            .addComponent(EdadTF)
                            .addComponent(IdClienteTF, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GuardarBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreLb)
                    .addComponent(NombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EspecieLb)
                    .addComponent(EspecieTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RazaLb)
                    .addComponent(RazaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EdadLb)
                    .addComponent(EdadTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GuardarBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdClienteLb)
                    .addComponent(IdClienteTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EliminarBtn)
                    .addComponent(ModificarBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarBtnActionPerformed
        // TODO add your handling code here:
        String nombre = NombreTF.getText().trim();
    String especie = EspecieTF.getText().trim();
    String raza = RazaTF.getText().trim();
    String edadStr = EdadTF.getText().trim();
    String idClienteStr = IdClienteTF.getText().trim();

    if (nombre.isEmpty() || idClienteStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "El nombre de la mascota y el ID del Cliente son obligatorios.");
        return;
    }

    try {
        int edad = edadStr.isEmpty() ? 0 : Integer.parseInt(edadStr);
        int idCliente = Integer.parseInt(idClienteStr);

        Mascota m = new Mascota(nombre, especie, raza, edad, idCliente);
        if (mascotaDAO.guardar(m)) {
            JOptionPane.showMessageDialog(this, "¡Mascota registrada correctamente!");
            listarMascotas();
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar mascota. Revisa que el ID del cliente exista en la base de datos.");
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "La edad y el ID Cliente deben ser números enteros.");
    }
    }//GEN-LAST:event_GuardarBtnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int fila = jTable1.getSelectedRow();
    if (fila != -1) {
        idMascotaSeleccionada = Integer.parseInt(jTable1.getValueAt(fila, 0).toString());
        NombreTF.setText(jTable1.getValueAt(fila, 1).toString());
        EspecieTF.setText(jTable1.getValueAt(fila, 2).toString());
        RazaTF.setText(jTable1.getValueAt(fila, 3).toString());
        EdadTF.setText(jTable1.getValueAt(fila, 4).toString());
        IdClienteTF.setText(jTable1.getValueAt(fila, 5).toString());
    }
    }//GEN-LAST:event_jTable1MouseClicked

    private void ModificarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarBtnActionPerformed
        // TODO add your handling code here:
        if (idMascotaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona una mascota de la tabla para modificar.");
        return;
    }

    String nombre = NombreTF.getText().trim();
    String especie = EspecieTF.getText().trim();
    String raza = RazaTF.getText().trim();
    String edadStr = EdadTF.getText().trim();
    String idClienteStr = IdClienteTF.getText().trim();

    try {
        int edad = edadStr.isEmpty() ? 0 : Integer.parseInt(edadStr);
        int idCliente = Integer.parseInt(idClienteStr);

        Mascota m = new Mascota(idMascotaSeleccionada, nombre, especie, raza, edad, idCliente);
        if (mascotaDAO.modificar(m)) {
            JOptionPane.showMessageDialog(this, "Mascota actualizada correctamente.");
            listarMascotas();
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Error al actualizar la mascota.");
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "La edad y el ID del cliente deben ser números válidos.");
    }
    }//GEN-LAST:event_ModificarBtnActionPerformed

    private void EliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBtnActionPerformed
        // TODO add your handling code here:
        if (idMascotaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona una mascota de la tabla para modificar.");
        return;
    }

    String nombre = NombreTF.getText().trim();
    String especie = EspecieTF.getText().trim();
    String raza = RazaTF.getText().trim();
    String edadStr = EdadTF.getText().trim();
    String idClienteStr = IdClienteTF.getText().trim();

    try {
        int edad = edadStr.isEmpty() ? 0 : Integer.parseInt(edadStr);
        int idCliente = Integer.parseInt(idClienteStr);

        Mascota m = new Mascota(idMascotaSeleccionada, nombre, especie, raza, edad, idCliente);
        if (mascotaDAO.modificar(m)) {
            JOptionPane.showMessageDialog(this, "Mascota actualizada correctamente.");
            listarMascotas();
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Error al actualizar la mascota.");
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "La edad y el ID del cliente deben ser números válidos.");
    }
    }//GEN-LAST:event_EliminarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormMascota().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EdadLb;
    private javax.swing.JTextField EdadTF;
    private javax.swing.JButton EliminarBtn;
    private javax.swing.JLabel EspecieLb;
    private javax.swing.JTextField EspecieTF;
    private javax.swing.JButton GuardarBtn;
    private javax.swing.JLabel IdClienteLb;
    private javax.swing.JTextField IdClienteTF;
    private javax.swing.JButton ModificarBtn;
    private javax.swing.JLabel NombreLb;
    private javax.swing.JTextField NombreTF;
    private javax.swing.JLabel RazaLb;
    private javax.swing.JTextField RazaTF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
