/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.huellitas.view;

/**
 *
 * @author yisha
 */
import com.huellitas.dao.ClienteDAO;
import com.huellitas.model.Cliente;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class FormCliente extends javax.swing.JFrame {

    ClienteDAO clienteDAO = new ClienteDAO();
    DefaultTableModel modeloTabla = new DefaultTableModel();
    int idClienteSeleccionado = -1;

    public FormCliente() {
        initComponents();
        this.setLocationRelativeTo(null); // Centra la ventana en pantalla
        listarClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombrelb = new javax.swing.JLabel();
        Telefonolb = new javax.swing.JLabel();
        Correolb = new javax.swing.JLabel();
        Direccionlb = new javax.swing.JLabel();
        NombreTF = new javax.swing.JTextField();
        TelefonoTF = new javax.swing.JTextField();
        CorreoTF = new javax.swing.JTextField();
        DireccionTF = new javax.swing.JTextField();
        GuardarBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        EliminarBtn = new javax.swing.JButton();
        ModificarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Nombrelb.setText("Nombre:");

        Telefonolb.setText("Teléfono:");

        Correolb.setText("Correo:");

        Direccionlb.setText("Dirección:");

        GuardarBtn.setText("Guardar");
        GuardarBtn.addActionListener(this::GuardarBtnActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Teléfono", "Correo", "Dirección"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        EliminarBtn.setText("Eliminar");
        EliminarBtn.addActionListener(this::EliminarBtnActionPerformed);

        ModificarBtn.setText("Modificar");
        ModificarBtn.addActionListener(this::ModificarBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Nombrelb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Telefonolb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Correolb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Direccionlb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NombreTF)
                            .addComponent(TelefonoTF)
                            .addComponent(CorreoTF, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                            .addComponent(DireccionTF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GuardarBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EliminarBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ModificarBtn)))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nombrelb)
                    .addComponent(NombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telefonolb)
                    .addComponent(TelefonoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Correolb)
                    .addComponent(CorreoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Direccionlb)
                    .addComponent(DireccionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GuardarBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EliminarBtn)
                    .addComponent(ModificarBtn))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBtnActionPerformed
        // TODO add your handling code here:
       if (idClienteSeleccionado == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona un cliente de la tabla para eliminar.");
        return;
    }

    int confirmacion = JOptionPane.showConfirmDialog(
        this, 
        "¿Deseas eliminar al cliente seleccionado?", 
        "Confirmar eliminación", 
        JOptionPane.YES_NO_OPTION
    );

    if (confirmacion == JOptionPane.YES_OPTION) {
        if (clienteDAO.eliminar(idClienteSeleccionado)) {
            JOptionPane.showMessageDialog(this, "Cliente eliminado.");
            listarClientes();
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Error al eliminar cliente.");
        }
    }
    }//GEN-LAST:event_EliminarBtnActionPerformed

    private void GuardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarBtnActionPerformed
        // TODO add your handling code here:
        String nombre = NombreTF.getText().trim();
    String telefono = TelefonoTF.getText().trim();
    String correo = CorreoTF.getText().trim();
    String direccion = DireccionTF.getText().trim();

    if (nombre.isEmpty()) {
        JOptionPane.showMessageDialog(this, "El nombre del cliente es obligatorio.");
        return;
    }

    Cliente c = new Cliente(nombre, telefono, correo, direccion);
    if (clienteDAO.guardar(c)) {
        JOptionPane.showMessageDialog(this, "¡Cliente registrado correctamente!");
        listarClientes();
        limpiarCampos();
    } else {
        JOptionPane.showMessageDialog(this, "Error al registrar cliente.");
    }
    }//GEN-LAST:event_GuardarBtnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int fila = jTable1.getSelectedRow();
    if (fila != -1) {
        idClienteSeleccionado = Integer.parseInt(jTable1.getValueAt(fila, 0).toString());
        NombreTF.setText(jTable1.getValueAt(fila, 1).toString());
        TelefonoTF.setText(jTable1.getValueAt(fila, 2).toString());
        CorreoTF.setText(jTable1.getValueAt(fila, 3).toString());
        DireccionTF.setText(jTable1.getValueAt(fila, 4).toString());
    }
    }//GEN-LAST:event_jTable1MouseClicked

    private void ModificarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarBtnActionPerformed
        // TODO add your handling code here:
        if (idClienteSeleccionado == -1) {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona un cliente de la tabla.");
        return;
    }

    String nombre = NombreTF.getText().trim();
    String telefono = TelefonoTF.getText().trim();
    String correo = CorreoTF.getText().trim();
    String direccion = DireccionTF.getText().trim();

    Cliente c = new Cliente(idClienteSeleccionado, nombre, telefono, correo, direccion);
    if (clienteDAO.modificar(c)) {
        JOptionPane.showMessageDialog(this, "Cliente actualizado correctamente.");
        listarClientes();
        limpiarCampos();
    } else {
        JOptionPane.showMessageDialog(this, "Error al actualizar cliente.");
    }
    }//GEN-LAST:event_ModificarBtnActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormCliente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CorreoTF;
    private javax.swing.JLabel Correolb;
    private javax.swing.JTextField DireccionTF;
    private javax.swing.JLabel Direccionlb;
    private javax.swing.JButton EliminarBtn;
    private javax.swing.JButton GuardarBtn;
    private javax.swing.JButton ModificarBtn;
    private javax.swing.JTextField NombreTF;
    private javax.swing.JLabel Nombrelb;
    private javax.swing.JTextField TelefonoTF;
    private javax.swing.JLabel Telefonolb;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void listarClientes() {
    List<Cliente> lista = clienteDAO.listar();
    modeloTabla = (DefaultTableModel) jTable1.getModel();
    modeloTabla.setRowCount(0); // Limpia la tabla
    
    for (Cliente c : lista) {
        Object[] fila = new Object[5];
        fila[0] = c.getIdCliente();
        fila[1] = c.getNombre();
        fila[2] = c.getTelefono();
        fila[3] = c.getCorreo();
        fila[4] = c.getDireccion();
        modeloTabla.addRow(fila);
    }
}

private void limpiarCampos() {
    NombreTF.setText("");
    TelefonoTF.setText("");
    CorreoTF.setText("");
    DireccionTF.setText("");
    idClienteSeleccionado = -1;
    jTable1.clearSelection();
}
}
